name: torch
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py312h6a678d5_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.1.0=h77fa898_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.9.2=py312h66fe004_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.10=py312h5eee18b_0
  - mkl_random=1.2.7=py312h526ad5a_0
  - ncurses=6.4=h6a678d5_0
  - nibabel=5.2.1=pyha770c72_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=py312h06a4308_0
  - pip=24.2=py312h06a4308_0
  - pybind11-abi=5=hd3eb1b0_0
  - pyparsing=3.1.2=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.5.1=py312h526ad5a_0
  - scipy=1.13.1=py312hc5e2394_0
  - setuptools=72.1.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - asttokens==2.4.1
      - debugpy==1.8.5
      - decorator==5.1.1
      - executing==2.1.0
      - filelock==3.13.1
      - fsspec==2024.2.0
      - jinja2==3.1.3
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.2
      - prompt-toolkit==3.0.47
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyzmq==26.2.0
      - stack-data==0.6.3
      - sympy==1.12
      - torch==2.4.0+cu118
      - torchaudio==2.4.0+cu118
      - torchvision==0.19.0+cu118
      - tornado==6.4.1
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.9.0
      - wcwidth==0.2.13
prefix: /home/Student/s4765132/miniconda3/envs/torch
