FirstRun: False
DatasetImageDir: "data/train-image/image"
LabelCSV: "data/train-metadata.csv"
OutputDir: "data/preprocessed"
TrainTestRario: 0.8
OversampleRatio: 0.6
BatchSize: 32
ModelDropoutRate: 0.3
TripletLossMargin: 1.0
LearningRate: 0.001
EpochCount: 16
